### ISSUE TITLE
Sample reads data missing.

### ISSUE THREAD

**Issue by yifangt** [Feathergunner/DebruijnGraphBuilder#1]
Hello sir:
When I tried your code, I always got error as:
```
File fast_debruijn_builder/data_io.py", line 19, in get_reads_from_fastq_file
    with open(filename) as fh:
IOError: [Errno 2] No such file or directory: 'Data/hcov229e_only.fq'

```
Is it possible for you to add this file for testing, please? I am trying to learn de Bruijn graph for genome  assembly. Thanks a lot!

**Comment by Feathergunner** [comment]
Hello,
I'm sorry, i can't add the file, it's very large. In general, the code should work with any file in "fastq"-format, just find something on the internet and update the filename in the specific line that gives the error. 
Note that you can also generate your own random dataset for testing. If you look at the file data_gen.py you will find some methods that create random "dna"-strings and sample reads from a string.
Please note also that this repository is primarly for my own documentation. At the moment I do not consider adding any kind of documentation or instruction how to use it.

**Comment by yifangt** [comment]
Thanks!

**Comment by yifangt** [comment]
Hello sir:
I can't help myself asking this question as I could not find a clear answer
on it!
How did you handle the reverse_complement strand for your de_bruijn graph?

I noticed your have the invert_id, but I could not find the rev_comp for
each kmers.
Because Illumina reads are randomly from the either strand, so the reverse
complementation is needed for each kmer.
1) If the rev_comp strands are used, there should be two resultant
sequences for the genome. Is this right? But in my practice with the
assemblers (SPADEs/Ray) I only got single strands.
2) I read some posts saying each kmer is complemented for the graph, but I
want to confirm if this is equivalent to rev_complement the reads before
kmer parsing.

My background is genomics/genetics and I'm interested in bioinformatics and
learning to code for genome assembly by myself for fun.
Lack of computer science background makes my question naive, but I hope to
get your possible help on this point when it is convenient to you.

Thank you very much!

Yifang

**Comment by Feathergunner** [comment]
My algorithm takes only the original reads, but adds both the original kmer and its inverse during graph construction (see fast_debruijn_graph_builder.py lines 331 ...). Then the de bruijn graph is constructed, and afterwards i delete one of the two directions (see lines 541 ...). This is very likely not a very good approach (because you construct every sequence twice), but it works for me. One problem occurs if a kmer and its inverse appear within the same component of the graph, then these kmers and all connected sequences are not deleted, and in particular both directions of all these sequences remain in the graph. Real assemblers may have implemented more intelligent ways to handle the reverse strands.

I think one could (instead of my approach) add the reverse complement for each read and construct kmers from this extended set of reads, the results should be the same.

I hope this helps!
